### ISSUE TITLE
Dockerfile only works with ingress version is explicitly set to 0.26.0

### ISSUE THREAD

**Issue by gargrag** [signalsciences/sigsci-nginx-ingress-controller#1]
If the `NGINX_INGRESS_VERSION` variable is not set, The Dockerfile fallbacks to ` `latest`.

https://quay.io/repository/kubernetes-ingress-controller/nginx-ingress-controller?tab=tags

They are not using the latest tag, so if the variable is not explicitly set, the build fails.

On the other hand, this builds only up to the nginx-ingress-controller version 0.26.0, with greater versions, build fails because of the linux distro.

```
docker build . -t asd                                                                                                                                                            (1) (*master+199) 10:37:19
Sending build context to Docker daemon  4.608kB
Step 1/6 : ARG NGINX_INGRESS_VERSION=0.27.0
Step 2/6 : FROM quay.io/kubernetes-ingress-controller/nginx-ingress-controller:${NGINX_INGRESS_VERSION}
0.27.0: Pulling from kubernetes-ingress-controller/nginx-ingress-controller
e6b0cf9c0882: Already exists
51aec138e7ac: Pull complete
2007b3d18a58: Pull complete
71898f99a183: Pull complete
0c944f0bf32d: Pull complete
6516c6eae2ed: Pull complete
d84dee1d9e38: Pull complete
21b658a8d968: Pull complete
e6665e5ebf9f: Pull complete
652cf80411d9: Pull complete
903ae8041709: Pull complete
Digest: sha256:4c2de59096259e862c8192d25e24830de89b6f6e0b8c8b2509757de56d0b793c
Status: Downloaded newer image for quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.27.0
 ---> 82d45c3086b4
Step 3/6 : ARG PKGNAME=${PKGNAME:-nginx-module-sigsci-nxo}
 ---> Running in b689b64e5f47
Removing intermediate container b689b64e5f47
 ---> 9a3f239e99e7
Step 4/6 : USER root
 ---> Running in 89920d45151c
Removing intermediate container 89920d45151c
 ---> 275f3da5c70e
Step 5/6 : RUN apt-get update && apt-get install -y apt-transport-https gnupg lsb-release     && CODENAME=$(lsb_release -c | sed 's/^Codename:\s*//')     && if [ "${CODENAME}" = "sid" ]; then CODENAME="buster"; fi     && NGXVERSION=$(nginx -v 2>&1 | sed 's%^[^/]*/\([0-9]*\.[0-9]*\.[0-9]*\).*%\1%')     && (curl -s -S -L https://apt.signalsciences.net/release/gpgkey | apt-key add -)     && (echo "deb https://apt.signalsciences.net/release/debian/ ${CODENAME} main" > /etc/apt/sources.list.d/sigsci-release.list)     && apt-get update     && apt-get download nginx-module-sigsci-nxo=${NGXVERSION}\*     && (dpkg --force-all -i nginx-module-sigsci-nxo_${NGXVERSION}*.deb || true)     && rm -f nginx-module-sigsci-nxo_${NGXVERSION}*.deb     && sed -i "s@^#pid.*@&\nload_module /usr/lib/nginx/modules/ngx_http_sigsci_nxo_module-${NGXVERSION}.so;\n@" /usr/local/openresty/nginx/conf/nginx.conf     && rm -rf /var/lib/apt/lists/*
 ---> Running in 91b82dffdbd2
/bin/sh: apt-get: not found
```

**Comment by leaf-sigsci** [comment]
Thanks for the report Gastón, we didn't have any packages available to easily install into alpine containers. We've added them, and are about to land changes that will work with the current ingress controller images.

**Comment by gargrag** [comment]
Hi @leaf-sigsci thanks for the reply. I see that now the Dockerfile seems to consider alpine.
We are experiencing a similar issue.

1.  nginx-ingress-controller image does not have a `latest` tag, so if you don't explicitly specify the variable `NGINX_INGRESS_VERSION`, the build fails

```
$ docker pull quay.io/kubernetes-ingress-controller/nginx-ingress-controller:latest
Error response from daemon: manifest for quay.io/kubernetes-ingress-controller/nginx-ingress-controller:latest not found: manifest unknown: manifest unknown
```

1.  If I set the version to `0.30.0` which is the latest as of today. the script detects alpine version `3_11` which is correct, and nginx_version `1.17.8` which is also correct, but then, when it tries to download the module, it fails. You only  have a module for Nginx version `1.17.9` under `alpine_3_11`, `alpine_3_10`, `alpine_3_9` and `alpine_3_8`
Even with the ingress controller version `0.27.0` the Nginx version is `1.17` alpine `3_11` and the build fails.

**Comment by alfred-sigsci** [comment]
hi @gargrag the issue with the missing builds mentioned here:

> If I set the version to 0.30.0 which is the latest as of today. the script detects alpine version 3_11 which is correct, and nginx_version 1.17.8 which is also correct, but then, when it tries to download the module, it fails. You only have a module for Nginx version 1.17.9 under alpine_3_11, alpine_3_10, alpine_3_9 and alpine_3_8

should be fixed now.  We are currently investigating the other issues you've observed and will keep you posted.

**Comment by audip** [comment]
Hi Signal Sciences team, 

I can't download the signal sciences package when trying to build this image for nginx ingress version 0.30.0 as it returns a HTTP 404 for the package

```
--2020-04-15 17:49:53--  https://dl.signalsciences.net/sigsci-module-nginx-native/1.0.41/alpine/alpine3_11/nginx-module-sigsci-nxo_1.17.8-146-alpine3_11.tar.gz
Resolving dl.signalsciences.net... 99.84.230.126, 99.84.230.4, 99.84.230.42, ...
Connecting to dl.signalsciences.net|99.84.230.126|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-15 17:49:53 ERROR 404: Not Found.
```

Can you check that package is uploaded on the right path?

**Comment by audip** [comment]
Thanks to @rocktavious for hacking on the URL to find the packages listed, and by using build number `151`, the docker image builds successfully. 

https://dl.signalsciences.net/?prefix=sigsci-module-nginx-native/1.0.41/alpine/alpine3_11/

**Comment by bbucher-sigsci** [comment]
The issue with the build number should be fixed now with this [change](https://github.com/signalsciences/sigsci-nginx-ingress-controller/commit/10a8f8201f1422a077a8b9b0a4eb3751c92dd1b1). It was determined that including the internal build number in the tar.gz file was not necessary, so we removed it.
