### ISSUE TITLE
Upgrade to nginx-ingress version 0.31.0

### ISSUE THREAD

**Issue by DanOfir** [signalsciences/sigsci-nginx-ingress-controller#4]
Hi,
Version 0.31.0 has some really important features and fixes we need. specially features for HTTP to https redirect.

when are you planning to upgrade the containers to support version 0.31.0?

**Comment by leaf-sigsci** [comment]
Apologies for the delay; 0.31.0, 0.32.0 and 0.33.0 compatible images have been published.
