### ISSUE TITLE
ARM64 Image is not working

### ISSUE THREAD

**Issue by lmad4832** [signalsciences/sigsci-nginx-ingress-controller#67]
Recently we tried to migrate our ingress workloads to ARM64 as a result we tried to migrate our signalscience integrated ingress controllers to ARM64 as well. Seems like this image is not working on ARM64 as it keeps restarting i.e crashing throwing the error below. 

Error : `exec /usr/bin/dumb-init: exec format error`

The same version's `kubernetes/nginx-ingress-controller` seems to be working fine in our ARM64 infrastructure. I feel like this has to be issue in the container image build pipeline where multi-arch images are not properly built. 

Versions tried : v1.10.0, v1.9.5

**Comment by jeremy-cxf** [comment]
Hey @lmad4832  - this should be fixed in #68 . We'll need to rebuild and push this, so we'll start off with latest and `v1.10.1` just to unstick you, than do it for a wider set of images afterwards.

**Comment by lmad4832** [comment]
@jeremy-cxf Thank you new version is working on our ARM64 nodes. 🔥
